import { useState } from 'react'
import { Activity, Bell, CalendarClock, Code2, LayoutDashboard, LogOut, Menu, Settings, Terminal, Users, X } from 'lucide-react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'

const links = [['/dashboard', 'Overview', LayoutDashboard], ['/interviews', 'Interview rooms', CalendarClock], ['/join', 'Join assessment', Terminal], ['/candidates', 'Candidates', Users], ['/activity', 'Activity', Activity]] as const

export function AppShell() {
  const [open, setOpen] = useState(false)
  const { username, logout } = useAuth()
  const navigate = useNavigate()
  const signOut = () => { logout(); navigate('/login') }
  return <div className="min-h-screen bg-[#0b0d11] text-[#e7e8ee]"><aside className={`fixed inset-y-0 left-0 z-30 w-[250px] border-r border-white/[.07] bg-[#0d0f14] px-5 py-6 transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center bg-[#f3c969] text-[#15130d]"><Code2 size={18} /></div><b className="tracking-[-.04em]">code<span className="text-[#f3c969]">jit</span></b></div><button className="lg:hidden" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18} /></button></div><nav className="mt-12 space-y-1">{links.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === '/dashboard'} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 px-3 py-2.5 text-sm font-semibold ${isActive ? 'bg-[#24201a] text-[#f3c969]' : 'text-[#858a98] hover:bg-white/[.04] hover:text-white'}`}><Icon size={17} /><span>{label}</span></NavLink>)}</nav><div className="absolute bottom-6 left-5 right-5 space-y-4"><NavLink to="/settings" className="flex items-center gap-3 px-3 py-2.5 text-sm font-semibold text-[#858a98]"><Settings size={17} />Settings</NavLink><div className="border-t border-white/[.07] pt-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center bg-[#252936] text-xs font-bold text-[#f3c969]">{(username ?? 'user').slice(0, 2).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-bold">{username ?? 'Authenticated user'}</p><p className="truncate text-xs text-[#7f8492]">Assessment workspace</p></div><button onClick={signOut} aria-label="Sign out" className="ml-auto text-[#7f8492] hover:text-[#f3c969]"><LogOut size={16} /></button></div></div></div></aside><main className="lg:ml-[250px]"><header className="flex h-[76px] items-center justify-between border-b border-white/[.07] px-5 sm:px-8"><div className="flex items-center gap-4"><button className="lg:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><span className="text-sm text-[#7f8492]">Workspace <span className="mx-2 text-[#414550]">/</span> <span className="text-[#e7e8ee]">CodeJit</span></span></div><button className="relative text-[#8f94a2]" aria-label="Notifications"><Bell size={18} /><i className="absolute -right-1 -top-1 h-1.5 w-1.5 bg-[#f3c969]" /></button></header><Outlet /></main></div>
}
