import { useState, type FormEvent } from 'react'
import { ArrowRight, Code2, LoaderCircle } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'

export function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const registering = mode === 'register'; const { login, register } = useAuth(); const navigate = useNavigate()
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { if (registering) await register(name, email, password); else await login(email, password); navigate('/dashboard') } catch (err) { setError(err instanceof Error ? err.message : 'Unable to authenticate') } finally { setLoading(false) } }
  return <div className="grid min-h-screen bg-[#0b0d11] lg:grid-cols-2"><div className="grid-noise hidden p-12 lg:flex lg:flex-col lg:justify-between"><Brand /><div><p className="mono text-xs uppercase tracking-[.2em] text-[#f3c969]">A better signal</p><h1 className="mt-5 max-w-lg text-6xl font-extrabold leading-none tracking-[-.07em] text-white">Where strong engineers <span className="text-[#f3c969]">show</span> their work.</h1></div><p className="mono text-[10px] text-[#686d7a]">CODEJIT / 2026</p></div><div className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><Brand /><p className="mono mt-10 text-xs uppercase tracking-[.2em] text-[#f3c969]">{registering ? 'Create account' : 'Welcome back'}</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-.06em] text-white">{registering ? 'Start your room.' : 'Pick up where you left off.'}</h2><form onSubmit={submit} className="mt-8 space-y-4">{registering && <Input value={name} onChange={setName} placeholder="Full name" />}{<Input value={email} onChange={setEmail} placeholder="Email" type="email" />}<Input value={password} onChange={setPassword} placeholder="Password" type="password" />{error && <p className="border border-[#683d38] bg-[#241716] p-3 text-xs text-[#f08c7d]">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 bg-[#f3c969] px-4 py-3 text-sm font-extrabold text-[#17140d]">{loading && <LoaderCircle className="animate-spin" size={16} />}{registering ? 'Create account' : 'Sign in'}{!loading && <ArrowRight size={16} />}</button></form><p className="mt-8 text-center text-sm text-[#858a98]">{registering ? 'Already have an account?' : 'New to CodeJit?'} <Link className="font-bold text-[#f3c969]" to={registering ? '/login' : '/register'}>{registering ? 'Sign in' : 'Create one'}</Link></p></div></div></div>
}
function Brand() { return <div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center bg-[#f3c969] text-[#15130d]"><Code2 size={18} /></div><b className="tracking-[-.04em]">code<span className="text-[#f3c969]">jit</span></b></div> }
function Input({ value, onChange, placeholder, type = 'text' }: { value: string; onChange: (value: string) => void; placeholder: string; type?: string }) { return <input required value={value} onChange={(event) => onChange(event.target.value)} type={type} placeholder={placeholder} className="w-full border border-white/[.12] bg-[#11141a] px-3 py-3 text-sm text-white outline-none placeholder:text-[#555a67] focus:border-[#f3c969]" /> }
