import { useEffect, useState, type FormEvent } from 'react'
import { CalendarPlus, Copy, Plus, Radio } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api, type Interview } from '../api'

export function InterviewSchedulePage() {
  const [interviews, setInterviews] = useState<Interview[]>([])
  const [error, setError] = useState('')
  const [showForm, setShowForm] = useState(false)
  useEffect(() => { api.interviews().then(setInterviews).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load interviews')) }, [])
  return <div className="grid-noise min-h-[calc(100vh-76px)] px-5 py-8 sm:px-8 lg:px-10 lg:py-12"><div className="mx-auto max-w-[1100px] slide-in"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mono text-[10px] uppercase tracking-[.22em] text-[#f3c969]">Interview rooms</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-.06em] text-white">Schedule a live screen.</h1><p className="mt-2 text-sm text-[#858a98]">Create a private room for conversation, collaboration, and code.</p></div><button onClick={() => setShowForm(!showForm)} className="flex items-center justify-center gap-2 bg-[#f3c969] px-4 py-3 text-sm font-extrabold text-[#17140d]"><Plus size={17} /> Schedule interview</button></div>{showForm && <ScheduleForm onCreated={(interview) => { setInterviews([interview, ...interviews]); setShowForm(false) }} />}{error && <p className="mt-6 border border-[#683d38] bg-[#241716] p-3 text-xs text-[#f08c7d]">{error}</p>}<div className="mt-10 flex items-center justify-between"><h2 className="text-xl font-extrabold text-white">Your rooms</h2><Link to="/interviews/join" className="text-xs font-bold text-[#f3c969]">Join with a code</Link></div><div className="mt-4 space-y-3">{interviews.map((interview) => <Link to={`/interviews/${interview.id}`} key={interview.id} className="group flex flex-col gap-4 border border-white/[.08] bg-[#11141a] p-5 transition hover:border-[#f3c969]/60 sm:flex-row sm:items-center"><div className="grid h-11 w-11 shrink-0 place-items-center bg-[#2a271d] text-[#f3c969]"><Radio size={19} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h3 className="font-extrabold text-white">{interview.title}</h3><span className="mono border border-white/[.15] px-2 py-1 text-[10px] text-[#f3c969]">{interview.status}</span></div><p className="mt-2 text-xs text-[#858a98]">{new Date(interview.scheduledStart).toLocaleString()} <span className="mx-2 text-[#4d515c]">·</span> {interview.participants.length} participant{interview.participants.length === 1 ? '' : 's'}</p></div><div className="flex items-center gap-2 border border-[#665a36] bg-[#242015] px-3 py-2"><span className="mono text-sm tracking-[.16em] text-[#f3c969]">{interview.shareCode}</span><button onClick={(event) => { event.preventDefault(); navigator.clipboard?.writeText(interview.shareCode) }} aria-label="Copy interview code" className="text-[#c6b776]"><Copy size={15} /></button></div></Link>)}{interviews.length === 0 && !error && <div className="border border-dashed border-white/[.14] p-10 text-sm text-[#858a98]">No interview rooms yet. Schedule the first one.</div>}</div></div></div>
}
function ScheduleForm({ onCreated }: { onCreated: (interview: Interview) => void }) { const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { onCreated(await api.createInterview({ title, description, scheduledStart: new Date(start).toISOString().slice(0, 19), scheduledEnd: new Date(end).toISOString().slice(0, 19) })) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to schedule interview') } }; return <form onSubmit={submit} className="mt-8 border border-[#3b3523] bg-[#181710] p-5 sm:p-6"><div className="flex items-center gap-3 text-[#f3c969]"><CalendarPlus size={19} /><h2 className="font-extrabold text-white">New interview room</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Interview title" className="border border-white/[.12] bg-[#11141a] px-3 py-3 text-sm text-white outline-none focus:border-[#f3c969] sm:col-span-2" /><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description (optional)" className="border border-white/[.12] bg-[#11141a] px-3 py-3 text-sm text-white outline-none focus:border-[#f3c969] sm:col-span-2" /><label className="text-xs text-[#858a98]">Starts<input required type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} className="mt-2 w-full border border-white/[.12] bg-[#11141a] px-3 py-3 text-sm text-white outline-none focus:border-[#f3c969]" /></label><label className="text-xs text-[#858a98]">Ends<input required type="datetime-local" value={end} onChange={(e) => setEnd(e.target.value)} className="mt-2 w-full border border-white/[.12] bg-[#11141a] px-3 py-3 text-sm text-white outline-none focus:border-[#f3c969]" /></label></div>{error && <p className="mt-4 text-xs text-[#f08c7d]">{error}</p>}<button className="mt-5 flex items-center gap-2 bg-[#f3c969] px-4 py-3 text-xs font-extrabold text-[#17140d]"><CalendarPlus size={15} /> Create room</button></form> }
